[package]
name = "macroquad_rapier_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
macroquad = {version = "0.4.13", features = ["audio"]}
rapier2d = "0.23.0"
xml-rs = "0.8.25"
